//
// Generated file, do not edit! Created by nedtool 5.0 from CellularMessage.msg.
//

#ifndef __CELLULARMESSAGE_M_H
#define __CELLULARMESSAGE_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0500
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
enum CellularMsgCC {
	TRANSMISSION_STARTING,
	TRANSMISSION_ENDING,
	DATA_PACKET_NORMAL,
	DATA_PACKET_LAST,
	DOWNLOADING_COMPLETING
};
// }}

/**
 * Class generated from <tt>CellularMessage.msg:30</tt> by nedtool.
 * <pre>
 * packet CellularMessage
 * {
 *     // @brief express which kind of control signaling message.
 *     // 0: request to start transmission;
 *     // 1: request to end transmission;
 *     // 2: normal data packet transmission;
 *     // 3: last data packet transmission;
 *     int controlCode;
 *     int downloader;  // identifier of downloader's application
 *     int contentSize; // content size of requested large volume file
 *     int curOffset;   // current content offset of the data this packet contains
 *     int startOffset; // start offset position of this content
 *     int endOffset;   // end offset position of this content
 * }
 * </pre>
 */
class CellularMessage : public ::omnetpp::cPacket
{
  protected:
    int controlCode;
    int downloader;
    int contentSize;
    int curOffset;
    int startOffset;
    int endOffset;

  private:
    void copy(const CellularMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const CellularMessage&);

  public:
    CellularMessage(const char *name=nullptr, int kind=0);
    CellularMessage(const CellularMessage& other);
    virtual ~CellularMessage();
    CellularMessage& operator=(const CellularMessage& other);
    virtual CellularMessage *dup() const {return new CellularMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
    virtual int getControlCode() const;
    virtual void setControlCode(int controlCode);
    virtual int getDownloader() const;
    virtual void setDownloader(int downloader);
    virtual int getContentSize() const;
    virtual void setContentSize(int contentSize);
    virtual int getCurOffset() const;
    virtual void setCurOffset(int curOffset);
    virtual int getStartOffset() const;
    virtual void setStartOffset(int startOffset);
    virtual int getEndOffset() const;
    virtual void setEndOffset(int endOffset);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CellularMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CellularMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef __CELLULARMESSAGE_M_H

