//
// Generated file, do not edit! Created by nedtool 5.0 from WiredMessage.msg.
//

#ifndef __WIREDMESSAGE_M_H
#define __WIREDMESSAGE_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0500
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "veins/modules/application/ContentUtils.h"

enum WiredMsgCC {
	START_TRANSMISSION,
	END_TRANSMISSION,
	NORMAL_DATA_PACKET,
	LAST_DATA_PACKET,
	COMPLETE_DOWNLOADING,
	COOPERATIVE_NOTIFICATION,
	COOPERATIVE_ACKNOWLEDGEMENT
};
// }}

/**
 * Class generated from <tt>WiredMessage.msg:37</tt> by nedtool.
 * <pre>
 * packet WiredMessage
 * {
 *     // @brief express which kind of control signaling message.
 *     // 0: request to start transmission;
 *     // 1: request to end transmission;
 *     // 2: normal data packet transmission;
 *     // 3: last data packet transmission;
 *     // 4: downloading process completion notification;
 *     // 5: notify neighbor RSU to participate in downloading process.
 *     int controlCode;
 *     int downloader;  // identifier of downloader's application
 *     int contentSize; // content size of requested large volume file
 *     int curOffset;   // current content offset of the data this packet contains
 *     int startOffset; // start offset position of this content
 *     int endOffset;   // end offset position of this content
 *     int bytesNum;    // this variable exists due to performance consideration, for sending many packets once in transmission
 *     Coord position;  // position of the co-downloader
 *     Coord speed;     // speed of the co-downloader
 *     NeighborItems neighbors; // neighbors of the co-downloader
 * }
 * </pre>
 */
class WiredMessage : public ::omnetpp::cPacket
{
  protected:
    int controlCode;
    int downloader;
    int contentSize;
    int curOffset;
    int startOffset;
    int endOffset;
    int bytesNum;
    Coord position;
    Coord speed;
    NeighborItems neighbors;

  private:
    void copy(const WiredMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const WiredMessage&);

  public:
    WiredMessage(const char *name=nullptr, int kind=0);
    WiredMessage(const WiredMessage& other);
    virtual ~WiredMessage();
    WiredMessage& operator=(const WiredMessage& other);
    virtual WiredMessage *dup() const {return new WiredMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
    virtual int getControlCode() const;
    virtual void setControlCode(int controlCode);
    virtual int getDownloader() const;
    virtual void setDownloader(int downloader);
    virtual int getContentSize() const;
    virtual void setContentSize(int contentSize);
    virtual int getCurOffset() const;
    virtual void setCurOffset(int curOffset);
    virtual int getStartOffset() const;
    virtual void setStartOffset(int startOffset);
    virtual int getEndOffset() const;
    virtual void setEndOffset(int endOffset);
    virtual int getBytesNum() const;
    virtual void setBytesNum(int bytesNum);
    virtual Coord& getPosition();
    virtual const Coord& getPosition() const {return const_cast<WiredMessage*>(this)->getPosition();}
    virtual void setPosition(const Coord& position);
    virtual Coord& getSpeed();
    virtual const Coord& getSpeed() const {return const_cast<WiredMessage*>(this)->getSpeed();}
    virtual void setSpeed(const Coord& speed);
    virtual NeighborItems& getNeighbors();
    virtual const NeighborItems& getNeighbors() const {return const_cast<WiredMessage*>(this)->getNeighbors();}
    virtual void setNeighbors(const NeighborItems& neighbors);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const WiredMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, WiredMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef __WIREDMESSAGE_M_H

